export { default as HomePage } from './Home';
export { default as AboutPage } from './About';
export { default as BlogPage } from './Blog';
export { default as PostPage } from './Post';
export { default as CreatePage } from './Create';
export { default as EditPage } from './Edit';
export { default as DeletePage } from './Delete';
export { default as LoginPage } from './Login';
export { default as RegisterPage } from './Register';